version: '3'
services: 
    java-env:
        build: .
        image: java/env
        command: echo env running!
    tomcat:
        build: ./tomcat
        image: tomcat
        ports: 
            - 5000:8080
        volumes: 
            - ./jenkins_home:/root/.jenkins
        depends_on: 
            - java-env
    eclipse:
        build: ./eclipse
        image: eclipse
        command: echo run ./eclipse/start_eclipse.sh to run eclipse
        depends_on: 
            - java-env
