version: '3'
services: 
    java-env:
        build: .
        image: java/env
        command: echo env running!
    eclipse:
        build: ./eclipse
        image: eclipse
        command: echo run ./eclipse/start_eclipse.sh to run eclipse
        depends_on: 
            - java-env
    netbeans:
        build: ./netbeans
        image: netbeans
        command: echo run ./netbeans/start_netbeans.sh to run netbeans
        depends_on: 
            - java-env
    tomcat:
        build: ./tomcat
        image: tomcat
        container_name: tomcat
        ports: 
            - 80:8080
        volumes: 
            - ./jenkins_home:/root/.jenkins
        depends_on: 
            - java-env

