version: '3'
services: 
    eclipse:
        build: .
        image: eclipse
        environment: 
            - DISPLAY  
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix 
            - ~/Workspace/EclipseProjects:/home/developer/workspace
        